Using NumPy, a developer can perform the following operations −

    Mathematical and logical operations on arrays.
    Fourier transforms and routines for shape manipulation.
    Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.


In [ ]:
# Show version
import numpy as np
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
# Create a null vector of size 10 
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# memory size of any array
Z = np.zeros((100,100))
print("{} bytes".format(Z.size * Z.itemsize))

80000 bytes


In [ ]:
# create vector contains 10 elements with value 2.5
Z = np.full(shape=10, fill_value=2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [ ]:
# Create a vector with values ranging 
Z = np.arange(10,50)
print(Z)
# step 2
Z1 = np.arange(10,50, 2)
print(Z1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
# Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)
print(type(Z))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
<class 'numpy.ndarray'>


In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Find indices of non-zero elements
x = np.array([1,2,0,0,4,0])
nz = np.nonzero(x)
print(nz)
print("Len of non zero is {}".format(len(nz[0])))
type(nz)

(array([0, 1, 4]),)
Len of non zero is 3


tuple

In [ ]:
# Create a 3x3 identity matrix
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a 4x4 identity matrix
Z = np.eye(4,k=1)
print(Z)
print("----------------------")
Z = np.eye(4,k=-1)
print(Z)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
----------------------
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# Create a 10x10 array with random values and find the minimum and maximum values
# Uniform [0,1) 
Z = np.random.random(size=(5,5))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print("Zmin = {}, Zmax = {}".format(Zmin, Zmax))

[[0.74167846 0.25429473 0.42990855 0.69449453 0.84235133]
 [0.62347267 0.35140022 0.35651    0.77692675 0.66419799]
 [0.11432176 0.60537892 0.38947983 0.09032907 0.17467236]
 [0.82013591 0.67971603 0.75236059 0.36524736 0.20168051]
 [0.35194389 0.05789441 0.20370213 0.96665196 0.17206567]]
Zmin = 0.05789441151740016, Zmax = 0.9666519552857366


In [ ]:
# Create a random vector of size 30 and find the mean value 
Z = np.random.random(30)
m = Z.mean()
print(Z)
print("mean = {}".format(m))

[0.44498068 0.30241914 0.19982613 0.62117129 0.96105599 0.6352071
 0.95985591 0.0267759  0.93249537 0.46886938 0.30055555 0.06348219
 0.31932241 0.8703669  0.49831843 0.30267738 0.77184801 0.66514611
 0.59472407 0.39746823 0.59647538 0.50083539 0.42959642 0.98499852
 0.75894779 0.76647718 0.00548267 0.6984356  0.90123732 0.97947021]
mean = 0.5652840881675358


In [ ]:
# Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[2:-2,2:-2] = 0
print(Z)
print("----------------------")
Z = np.zeros((10,10))
Z[1:-1, 1:-1] = 1
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
----------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# interesting examples of some operations
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
3 * 0.1


nan
False
False
False
nan
True
False


0.30000000000000004

In [ ]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# Normalize a 5x5 random matrix
Z = np.random.random((5,5))
print(Z)
print("-------------------------")
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)


[[0.62188277 0.894708   0.02766097 0.83666416 0.76237745]
 [0.38298407 0.89908394 0.8597793  0.59450992 0.98141745]
 [0.62344732 0.64917459 0.86089107 0.42991843 0.67730192]
 [0.06976977 0.24091615 0.60987043 0.03610811 0.91091555]
 [0.19907516 0.33841836 0.73330568 0.48460537 0.05673312]]
-------------------------
[[ 0.23418247  1.13887061 -1.73625624  0.94639731  0.70006267]
 [-0.5580053   1.15338122  1.02304707  0.14341413  1.42639902]
 [ 0.23937055  0.32468213  1.0267337  -0.40237101  0.41795231]
 [-1.5966235  -1.02910234  0.19434958 -1.70824554  1.1926148 ]
 [-1.16784702 -0.70578512  0.60366073 -0.22102919 -1.63985303]]


In [ ]:
#  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
a = np.ones((5,3))
b = np.ones((3,2))
Z = np.dot(a, b)
print(a)
print(b)
print("Product")
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Product
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# Given a 1D array, negate all elements located between 3 and 8
Z = np.arange(11)
print("Original\n",Z)
Z[(3 < Z) & (Z <= 8)] *= -1
# Break it down
trueFalseCollection = (3 < Z) & (Z <= 8)
print("trueFalseCollection =", trueFalseCollection)
print("type(trueFalseCollection) =", type(trueFalseCollection))

print(Z)
print("Negate at selected indexes")
newTrueFalseArray = np.array([False, False, True, True, True, True, True, True, True, True, True])
mySubset = Z[(newTrueFalseArray)] 
print("mySubset =", mySubset)

Original
 [ 0  1  2  3  4  5  6  7  8  9 10]
trueFalseCollection = [False False False False False False False False False False False]
type(trueFalseCollection) = <class 'numpy.ndarray'>
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
Negate at selected indexes
mySubset = [ 2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# Given a 1D array, negate all elements located between 3 and 8
Z = np.arange(11)
print("Original\n",Z)
# Z[(3 < Z) & (Z <= 8)] *= -1
Z[[1,2,3]]*= -1
print(Z)

Original
 [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1 -2 -3  4  5  6  7  8  9 10]


In [ ]:
# compare two array
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print("-----------")
print(equal)

[0 1 0 1 1]
[1 0 1 0 1]
-----------
False


In [25]:
# create constant (immutable) array
# print("abc".flags) # only numpy?
Z = np.zeros(10)
Z.flags.writeable = False
print("Z.flags:\n", Z.flags)
print(dir(Z.flags))
Z[0] = 1



AttributeError: ignored

In [33]:
# get all the dates corresponding to the month of September 2020
Z = np.arange('2020-09', '2020-10', dtype='datetime64[W]')
print(Z)

['2020-08-27' '2020-09-03' '2020-09-10' '2020-09-17' '2020-09-24']


In [ ]:
# Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)
print(Z)
print("---------")
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[2.07978566 4.63978214 4.92857209 3.22003676 4.02664366 0.61398076
 3.52872254 6.36647363 1.96988328 1.07563051]
---------
[2. 4. 4. 3. 4. 0. 3. 6. 1. 1.]
[2. 4. 4. 3. 4. 0. 3. 6. 1. 1.]
[2. 4. 4. 3. 4. 0. 3. 6. 1. 1.]
[2 4 4 3 4 0 3 6 1 1]
[2. 4. 4. 3. 4. 0. 3. 6. 1. 1.]


In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# transform int array to float
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Several routines are available in NumPy package for manipulation of elements in ndarray object. They can be classified into the following types

**Changing Shape**

In [ ]:
# This function returns a copy of an array collapsed into one dimension. The function takes the following parameters.
a = np.arange(8).reshape(2,4) 
print(a)
print("----------------")
print(a.flatten())
print("----------------")
"""
 	

order
'C'− row major default. 
'F': column major 
'A': flatten in column-major order, if a is Fortran contiguous in memory, row-major order otherwise 
'K': flatten a in the order the elements occur in the memory
"""
print( a.flatten(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
----------------
[0 1 2 3 4 5 6 7]
----------------
[0 4 1 5 2 6 3 7]


In [ ]:
a = np.arange(8).reshape(2,4) 
print(a)
print("----------------")
print(a.ravel())
("----------------")
print(a.ravel(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
----------------
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


**Transpose Operations**

In [ ]:
# This function permutes the dimension of the given array. It returns a view wherever possible. The function takes the following parameters.
a = np.arange(12).reshape(3,4)
print(a)
print("----------------")
print(np.transpose(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**Joining Arrays**

In [ ]:
# Concatenation refers to joining. This function is used to join two or more arrays of the same shape 
# along a specified axis. The function takes the following parameters
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
print(a)
print("------------------")
print(b)
print("------------------")
print(np.concatenate((a,b)))
print("------------------")
print(np.concatenate((a,b),axis = 1))

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# This function joins the sequence of arrays along a new axis. 
# Another level of brackets comparing to the above cell. 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
print(a)
print("------------------")
print(b)
print("------------------")
print(np.stack((a,b),0))
print("------------------")
print(np.stack((a,b),1))

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


**Statistical Functions**

In [38]:
# Percentile (or a centile) is a measure used in statistics 
# indicating the value below which a given percentage of observations 
# in a group of observations fall. 
# The function numpy.percentile() takes the following arguments.
"""
numpy.percentile(a, q, axis)
a - Input array
q - The percentile to compute must be between 0-100
axis - The axis along which the percentile is to be calculat
"""
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
# 10 20 30 40 50 60 70 80 90
print("np.percentile(a,50) =", np.percentile(a,50))
b = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("np.percentile(b,55) =", np.percentile(b,55))


np.percentile(a,50) = 50.0
np.percentile(b,55) = 54.0


In [ ]:
# Median is defined as the value separating the higher half of a data sample from the lower half. The numpy.median() function is used as shown in the following program.
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 
print(a)
print("----------------")
print(np.median(a))
print("----------------")
print(np.median(a, axis = 1))


[[30 65 70]
 [80 95 10]
 [50 90 60]]
----------------
65.0
----------------
[65. 80. 60.]


In [43]:
# Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. 
a = np.array([1,2,3,4]) 
print(np.average(a))
myWeights = [1, 2, 3, 2]
print(np.average(a, weights=myWeights))
mySum = sum(myWeights)
myNormedWeights = np.array(myWeights) / mySum
print(np.average(a, weights=myNormedWeights))


2.5
2.75
2.75


In [46]:
# Standard deviation is the square root of the average of squared deviations from mean.
print(np.std([1,2,3,4]))
print((np.std([1,2,3,4])) ** 2)



1.118033988749895
1.2500000000000002


In [45]:
# Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). In other words, the standard deviation is the square root of variance.
print(np.var([1,2,3,4]))

1.25
