# In this section, we will try to estimate the population mean with the help of bootstrap sampling. Let’s import the required libraries:

Бутстрап - это широко применяемый и чрезвычайно мощный статистический инструмент, который можно использовать для количественной оценки неопределенности, связанной с данным или методом статистического обучения.

In [7]:
import numpy as np
import seaborn as sns
import random

In [8]:
# normal distribution 
x = np.random.normal(loc= 500.0, scale=1.0, size=10000)
np.mean(x)

499.98932369709433

Now, we will draw 40 samples of size 5 from the distribution (population) and compute the mean for every sample:

In [11]:
sample_mean = []

# Bootstrap Sampling
for i in range(40):
  y = random.sample(x.tolist(), 5)
  avg = np.mean(y)
  print(np.sort(y))
  sample_mean.append(avg)

[499.53526525 499.77136192 500.04797563 500.21538715 501.79944973]
[499.85657738 499.91730055 500.37250353 500.37398871 500.77390004]
[498.9431652  499.32970266 499.70673144 499.9534267  501.26271751]
[496.97424437 499.78363709 499.94487193 500.54892331 500.86002721]
[499.65877463 499.68225172 499.95365883 500.2047965  500.73815527]
[497.95564755 499.58997074 500.81898995 501.00438214 501.46746328]
[498.52133745 499.29854358 499.78477528 500.51819581 502.39447981]
[499.08929163 499.37168889 499.61990362 499.81518737 500.97890638]
[499.5789617  499.61433027 500.53052024 501.13269067 501.66400683]
[498.70908071 498.7441622  500.00609069 500.17614625 501.03934317]
[498.82162318 499.35260023 499.47400116 500.11658533 500.26423567]
[498.98486849 499.91732573 500.39510369 500.53252649 500.61239528]
[498.44260071 499.56248701 499.85661302 500.72422424 501.72199335]
[499.32245217 499.52084347 499.68346675 500.01494729 500.73234247]
[498.72170887 499.47161412 501.15125598 502.07684879 502.28902

Let’s check the average of the mean values of all the 40 samples:

In [10]:
np.mean(sample_mean)

499.92471756128816

It turns out to be pretty close to the population mean! This is why Bootstrap Sampling is such a useful technique in statistics and machine learning.