In [1]:
import numpy as np
x = np.array([[1], 
              [2], 
              [3], 
              [4]])
y = np.array([[1], 
              [3], 
              [5], 
              [4]])
x_train = x[:2]
x_train

array([[1],
       [2]])

In [2]:
x_test = x[2:]
x_test

array([[3],
       [4]])

In [3]:
y_train = y[:2]
y_test = y[2:]


In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
reg_model = LinearRegression()
reg_model.fit(x_train, y_train)
y_pred_test = reg_model.predict(x_test)
test_mse1 = mean_squared_error(y_test, y_pred_test)
test_mse1

4.499999999999997

Swap test and train

In [5]:
x_train, x_test = x_test, x_train
y_train, y_test = y_test, y_train

Now the same code as before, but mse_2

In [6]:
reg_model = LinearRegression()
reg_model.fit(x_train, y_train)
y_pred_test = reg_model.predict(x_test)
test_mse2 = mean_squared_error(y_test, y_pred_test)
test_mse2

22.499999999999996

In [7]:
mse_2fold = np.mean([test_mse1, test_mse2])
mse_2fold

13.499999999999996

Now the same, but using the special library

In [8]:
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits = 2)
reg_model = LinearRegression()
mse_array = cross_val_score(estimator=reg_model, X=x, y=y, cv=kfold, scoring='neg_mean_squared_error')
mse_array


array([-22.5,  -4.5])

In [9]:
-np.mean(mse_array)

13.499999999999996

In [10]:
import sklearn
# Look at the possible metrics and find the one corresponding to MSE:
print(sorted(sklearn.metrics.SCORERS.keys()))

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'max_error', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_root_mean_squared_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weighted', 'roc_auc_ovr', 'roc_auc_ovr_weighted', 'v_measure_score']


In [11]:
from sklearn.model_selection import RepeatedKFold
rkf = RepeatedKFold(n_splits=2, n_repeats=2)
reg_model = LinearRegression()
mse_array = cross_val_score(estimator=reg_model, X=x, y=y, cv=rkf, scoring='neg_mean_squared_error')
mse_array, -np.mean(mse_array)

(array([-22.5,  -4.5,  -2.5,  -4.5]), 8.499999999999998)

Leave one out (LOO). If by hand, we can do 4 fits, take their 4 MSE's and average them up. But it takes space. We do it just by using the lbrary this time. 

In [12]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
reg_model = LinearRegression()
mse_array = cross_val_score(estimator=reg_model, X=x, y=y, cv=loo, scoring='neg_mean_squared_error')
mse_array, -np.mean(mse_array)

(array([-4.        , -0.18367347, -2.93877551, -9.        ]),
 4.030612244897958)

You can also do the same with the following classes:

In [13]:
from sklearn.model_selection import LeavePOut

In [14]:
from sklearn.model_selection import ShuffleSplit

In [15]:
from sklearn.model_selection import StratifiedKFold