In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

!pip install pydataset
from pydataset import data


In [14]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
df = pd.read_csv(url, names = headernames)
print(df.head())
print(df.tail())

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
     sepal-length  sepal-width  petal-length  petal-width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica


In [15]:
# Values convert to np array
X = df.iloc[:, :-1].values
y = df.iloc[:, 4].values

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state=42)

In [17]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
pd.DataFrame(X_train).head()

0             1         2         3
0  0.591421 -7.423075e-01  0.621190  0.746254
1 -1.252502  9.897433e-01 -1.146157 -1.394395
2 -1.006646 -3.296507e-15 -1.322892 -1.394395
3 -0.883717  7.423075e-01 -1.263980 -0.993023
4 -0.269076 -7.423075e-01  0.208809  0.077301

In [18]:
K = 8
classifier = KNeighborsClassifier(n_neighbors = K)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       0.95      1.00      0.97        19
 Iris-virginica       1.00      0.94      0.97        18

       accuracy                           0.98        60
      macro avg       0.98      0.98      0.98        60
   weighted avg       0.98      0.98      0.98        60

Accuracy: 0.9833333333333333


In [21]:
# Avalible dataset
data()

dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [22]:
# As Regressor
df = data("turnout")
X = df[['age','income','vote']]
y = df['educate']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3,random_state=0) 
df.tail()

race  age  educate  income  vote
1996  white   26     16.0  3.3834     0
1997  white   34     12.0  2.9170     1
1998  white   51     16.0  7.8949     1
1999  white   22     10.0  2.4811     0
2000  white   59     10.0  0.5523     0

In [23]:
k = 10
clf = KNeighborsRegressor(k)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)



print(mean_squared_error(y_test,y_pred))



9.2687375
