In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
import numpy as np
import pprint as pp
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix
from sklearn import datasets





In [ ]:
X = [[1, 1], 
     [2, 2], 
     [3, 1], 
     [1, 3], 
     [2, 1], 
     [3, 1]]
X = np.array(X)
y = np.array([0, 0, 0, 1, 1, 1])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.50, random_state=42)

clf = MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
clf.fit(X=X_train, y=y_train, sample_weight=None)

y_pred = clf.predict(X_test)
print(" prediction - ", y_pred, "\n")
result = confusion_matrix(y_test, y_pred)
print(" Confusion matrix:\n", result, "\n =================\n\n")
result1 = classification_report(y_test, y_pred)
print(" Classification Report:\n", result1, )


 prediction -  [1 1 0] 

 Confusion matrix:
 [[0 2]
 [1 0]] 


 Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



In [ ]:
print("coef: ", clf.coef_)
print("intercept: ", clf.intercept_)
print("class_log_prior: ", clf.class_log_prior_)

coef:  [[-0.81093022 -0.58778666]]
intercept:  [-0.40546511]
class_log_prior:  [-1.09861229 -0.40546511]


MultinomialNB for iris dataset

In [ ]:
iris_database = load_iris()
df_iris = pd.DataFrame(iris_database.data, columns=iris_database["feature_names"])
df_iris["target"] = iris_database["target"]
df_iris

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
   iris_database.data, iris_database["target"], test_size = 0.3, random_state = 1)

In [ ]:
print(" ===== X_train ====\n", X_train[:5], "\n==================")
print("===== y_train ====\n", y_train[:5], "\n==================")

 ===== X_train ====
 [[7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]] 
===== y_train ====
 [2 0 0 0 1] 


In [ ]:
print(" ===== X_test ====\n", X_test[:5], "\n==================")
print("===== y_test ====\n", y_test[:5], "\n==================")

 ===== X_test ====
 [[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]
 [7.9 3.8 6.4 2. ]] 
===== y_test ====
 [0 1 1 0 2] 


In [ ]:


clf = MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
clf.fit(X=X_train, y=y_train, sample_weight=None)

y_pred = clf.predict(X_test)
print(" prediction - ", y_pred, "\n")

result = confusion_matrix(y_test, y_pred)
print(" Confusion matrix:\n", result, "\n =================\n\n")

result1 = multilabel_confusion_matrix(y_test, y_pred)
print(" multilabel CM:\n", result1, "\n=================\n\n")

result2 = classification_report(y_test, y_pred)
print(" Classification Report:\n", result2, )

 prediction -  [0 1 1 0 2 2 2 0 0 2 2 0 2 2 2 0 2 2 0 0 2 2 2 0 2 2 0 0 2 2 2 2 2 2 2 0 2
 0 2 2 2 0 2 2 2] 

 Confusion matrix:
 [[14  0  0]
 [ 0  2 16]
 [ 0  0 13]] 


 multilabel CM:
 [[[31  0]
  [ 0 14]]

 [[27  0]
  [16  2]]

 [[16 16]
  [ 0 13]]] 


 Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.11      0.20        18
           2       0.45      1.00      0.62        13

    accuracy                           0.64        45
   macro avg       0.82      0.70      0.61        45
weighted avg       0.84      0.64      0.57        45



In [ ]:
print("coef: ", clf.coef_)
print("intercept: ", clf.intercept_)
print("class_log_prior: ", clf.class_log_prior_)

coef:  [[-0.71005211 -1.0953201  -1.90974863 -3.65616942]
 [-0.87573089 -1.64230055 -1.21524919 -2.37223349]
 [-0.96429479 -1.73906734 -1.12797923 -2.12546736]]
intercept:  [-1.07044141 -1.18822445 -1.04304244]
class_log_prior:  [-1.07044141 -1.18822445 -1.04304244]
