In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from plotly import graph_objects as go
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [ ]:
X_pure = np.array([[1, 3], [2, 1], [3, 8], [4, 5], [5, 2]])
y = np.array([2, 1, 6, 7, 9])

In [ ]:
X = np.hstack((np.ones(len(X)).reshape(-1, 1), X_pure))
X

array([[1., 1., 3.],
       [1., 2., 1.],
       [1., 3., 8.],
       [1., 4., 5.],
       [1., 5., 2.]])

In [ ]:
reg = LinearRegression(fit_intercept=True)
reg.fit(X_pure, y)
reg.intercept_, reg.coef_


(-1.9473684210526265, array([1.94078947, 0.29605263]))

In [ ]:
pca = PCA(n_components=2)
Z = pca.fit_transform(X_pure)
reg = LinearRegression(fit_intercept=True)
reg.fit(Z, y)
reg.intercept_, reg.coef_

(5.0, array([0.47880434, 1.90395834]))

In [ ]:
reg = LinearRegression(fit_intercept=False)
reg.fit(X, y)
reg.intercept_, reg.coef_

(0.0, array([-1.94736842,  1.94078947,  0.29605263]))

In [ ]:
pca = PCA(n_components=3)
Z = pca.fit_transform(X)
reg = LinearRegression(fit_intercept=False)
reg.fit(Z, y)
reg.intercept_, reg.coef_

(0.0, array([0.47880434, 1.90395834, 0.        ]))

In [ ]:
Z

array([[-0.98609584, -1.91510183,  0.        ],
       [-2.88222739, -0.7299077 , -0.        ],
       [ 4.18106408, -0.39837562,  0.        ],
       [ 1.28944108,  0.88166984,  0.        ],
       [-1.60218193,  2.16171531,  0.        ]])

In [ ]:
pca.transform([reg.coef_])

array([[-3.88682852, -0.73066502, -0.52119566]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss = StandardScaler(with_std=False).fit(X_pure)
X_centred = ss.transform(X_pure)
X_centred

array([[-2. , -0.8],
       [-1. , -2.8],
       [ 0. ,  4.2],
       [ 1. ,  1.2],
       [ 2. , -1.8]])

In [ ]:
 X_pure

array([[1, 3],
       [2, 1],
       [3, 8],
       [4, 5],
       [5, 2]])

In [ ]:
pca = PCA(n_components=2)
Z = pca.fit_transform(X_centred)
Z, Z.mean(axis=0)

(array([[-0.98609584, -1.91510183],
        [-2.88222739, -0.7299077 ],
        [ 4.18106408, -0.39837562],
        [ 1.28944108,  0.88166984],
        [-1.60218193,  2.16171531]]),
 array([ 1.33226763e-16, -8.88178420e-17]))

In [ ]:
Z_nc = pca.fit_transform(X_pure)
Z_nc

array([[-0.98609584, -1.91510183],
       [-2.88222739, -0.7299077 ],
       [ 4.18106408, -0.39837562],
       [ 1.28944108,  0.88166984],
       [-1.60218193,  2.16171531]])

In [ ]:
reg = LinearRegression()
reg.fit(X_centred, y)
reg.intercept_, reg.coef_

(5.0, array([1.94078947, 0.29605263]))

In [ ]:
reg = LinearRegression()
reg.fit(Z, y)
reg.intercept_, reg.coef_

(5.0, array([0.47880434, 1.90395834]))

In [ ]:
pca.transform([reg.coef_])

array([[-2.12663205, -2.32998662]])