In [ ]:
import numpy as np
import pandas as pd

x1 = np.array([[3], 
              [10], 
              [4], 
              [6]])
x2 = np.array([[5], 
              [7], 
              [12],
            [14]])
y = np.array([[13], 
              [14], 
              [17],
              [22]])
myMatrix = np.hstack([x1, x2, y])
df = pd.DataFrame(myMatrix, columns=['x1', 'x2', 'y'])
print(df)
df.shape

   x1  x2   y
0   1   3  11
1   8   5  12
2   2  10  15
3   4  12  20


(4, 3)

In [ ]:
from plotly import graph_objects as go 
scatter = go.Scatter3d(x=df['x1'], y=df['x2'], z=df['y'], mode='markers')
fig = go.Figure(data=scatter)
fig.show()


In [ ]:
# import numpy as np
# import pandas as pd
# from statsmodels.formula.api import ols

# data = np.array([[1,3,11], [8,5,12], [2,10,15]])
# df = pd.DataFrame(data, columns=['x1', 'x2', 'y'])

# reg = ols('y ~ 1 + x1', data=df).fit()
# reg = ols('__________', data=df).fit()
# print(reg.summary())

In [ ]:
%%script false
data = np.array([[1,3,11], [8,5,12], [2,10,15]])
df = pd.DataFrame(data, columns=['x1', 'x2', 'y'])
print(df)

In [ ]:
from statsmodels.formula.api import ols
from sklearn.metrics import mean_squared_error

reg0 = ols('y ~ 1', data=df).fit()
print("reg0.mse_model =", reg0.mse_model)
print("reg0.mse_resid =", reg0.mse_resid)
print("reg0.mse_total =", reg0.mse_total)
print(reg0.resid)
print("reg0.resid**2 = \n", reg0.resid**2)
print("np.sum(reg0.resid**2) / (4-1) = ", np.sum(reg0.resid**2) / (4-1))
ypred0 = reg0.predict(df)
ypred0
print("mean_squared_error(df.y, ypred0) =", mean_squared_error(df.y, ypred0))
print(reg0.summary().tables[0])
print(reg0.summary().tables[1])


reg0.mse_model = nan
reg0.mse_resid = 16.333333333333332
reg0.mse_total = 16.333333333333332
0   -3.5
1   -2.5
2    0.5
3    5.5
dtype: float64
reg0.resid**2 = 
 0    12.25
1     6.25
2     0.25
3    30.25
dtype: float64
np.sum(reg0.resid**2) / (4-1) =  16.333333333333332
mean_squared_error(df.y, ypred0) = 12.25
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Sat, 17 Jul 2021   Prob (F-statistic):                nan
Time:                        18:27:52   Log-Likelihood:                -10.687
No. Observations:                   4   AIC:                             23.37
Df Residuals:                       3   BIC:                             22.76
Df Model:                           0                 

/usr/local/lib/python3.7/dist-packages/statsmodels/regression/linear_model.py:1657: RuntimeWarning:

invalid value encountered in double_scalars

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.



In [ ]:
reg1 = ols('y ~ 1 + x1', data=df).fit()
print("reg1.mse_model =", reg1.mse_model)
print("reg1.mse_resid =", reg1.mse_resid)
print("reg1.mse_total =", reg1.mse_total)
print(reg1.resid)
print("reg1.resid**2 = \n", reg1.resid**2)
print("np.sum(reg1.resid**2) / (4-2) = ", np.sum(reg1.resid**2) / (4-2))
ypred1 = reg1.predict(df)
ypred1
print("mean_squared_error(df.y, ypred1)", mean_squared_error(df.y, ypred1))
print(reg1.summary().tables[0])
print(reg1.summary().tables[1])

reg1.mse_model = 0.008695652173898338
reg1.mse_resid = 24.49565217391305
reg1.mse_total = 16.333333333333332
0   -3.547826
1   -2.426087
2    0.469565
3    5.504348
dtype: float64
reg1.resid**2 = 
 0    12.587070
1     5.885898
2     0.220491
3    30.297845
dtype: float64
np.sum(reg1.resid**2) / (4-2) =  24.49565217391305
mean_squared_error(df.y, ypred1) 12.247826086956525
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.500
Method:                 Least Squares   F-statistic:                 0.0003550
Date:                Sat, 17 Jul 2021   Prob (F-statistic):              0.987
Time:                        18:27:52   Log-Likelihood:                -10.686
No. Observations:                   4   AIC:                             25.37
Df Residuals:                       2   BIC:                           

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.



In [ ]:
reg2 = ols('y ~ 1 + x2', data=df).fit()
print("reg2.mse_model =", reg2.mse_model)
print("reg2.mse_resid =", reg2.mse_resid)
print("reg2.mse_total =", reg2.mse_total)
print(reg2.resid)
print("reg2.resid**2 = \n", reg2.resid**2)
print("np.sum(reg2.resid**2) / (4-2) = ", np.sum(reg2.resid**2) / (4-2))
ypred2 = reg2.predict(df)
ypred2
print("mean_squared_error(df.y, ypred2)", mean_squared_error(df.y, ypred2))
print(reg2.summary().tables[0])
print(reg2.summary().tables[1])

reg2.mse_model = 43.47169811320755
reg2.mse_resid = 2.7641509433962246
reg2.mse_total = 16.333333333333332
0    0.575472
1   -0.235849
2   -1.764151
3    1.424528
dtype: float64
reg2.resid**2 = 
 0    0.331168
1    0.055625
2    3.112229
3    2.029281
dtype: float64
np.sum(reg2.resid**2) / (4-2) =  2.7641509433962246
mean_squared_error(df.y, ypred2) 1.3820754716981123
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.887
Model:                            OLS   Adj. R-squared:                  0.831
Method:                 Least Squares   F-statistic:                     15.73
Date:                Sat, 17 Jul 2021   Prob (F-statistic):             0.0581
Time:                        18:27:52   Log-Likelihood:                -6.3229
No. Observations:                   4   AIC:                             16.65
Df Residuals:                       2   BIC:                             15.

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.



In [ ]:
reg12 = ols('y ~ 1 + x1 + x2', data=df).fit()
print("reg12.mse_model =", reg12.mse_model)
print("reg12.mse_resid =", reg12.mse_resid)
print("reg12.mse_total =", reg12.mse_total)
print(reg12.resid)
print("reg12.resid**2 = \n", reg12.resid**2)
print("np.sum(reg12.resid**2) / (4-3) = ", np.sum(reg12.resid**2) / (4-3))
ypred12 = reg12.predict(df)
ypred12
print("mean_squared_error(df.y, ypred12)", mean_squared_error(df.y, ypred12))
print(reg12.summary().tables[0])
print(reg12.summary().tables[1])


reg12.mse_model = 21.748685507722644
reg12.mse_resid = 5.502628984554713
reg12.mse_total = 16.333333333333332
0    0.661518
1   -0.360828
2   -1.713934
3    1.413244
dtype: float64
reg12.resid**2 = 
 0    0.437606
1    0.130197
2    2.937568
3    1.997257
dtype: float64
np.sum(reg12.resid**2) / (4-3) =  5.502628984554713
mean_squared_error(df.y, ypred12) 1.3756572461386782
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.663
Method:                 Least Squares   F-statistic:                     3.952
Date:                Sat, 17 Jul 2021   Prob (F-statistic):              0.335
Time:                        18:27:52   Log-Likelihood:                -6.3136
No. Observations:                   4   AIC:                             18.63
Df Residuals:                       1   BIC:                           

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.

/usr/local/lib/python3.7/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning:

omni_normtest is not valid with less than 8 observations; 4 samples were given.



                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.5891      3.198      2.373      0.254     -33.041      48.219
x1             0.0299      0.438      0.068      0.957      -5.533       5.593
x2             0.9065      0.322      2.811      0.218      -3.191       5.004


In [ ]:
import statsmodels.formula.api as smf

def forward_selected(data, response):
    """Linear model designed by forward selection.

    Parameters:
    -----------
    data : pandas DataFrame with all possible predictors and response

    response: string, name of response column in data

    Returns:
    --------
    model: an "optimal" fitted statsmodels linear model
           with an intercept
           selected by forward selection
           evaluated by adjusted R-squared
    """
    remaining = set(data.columns)
    remaining.remove(response)
    selected = []
    current_score, best_new_score = 0.0, 0.0
    while remaining and current_score == best_new_score:
        scores_with_candidates = []
        for candidate in remaining:
            formula = "{} ~ {} + 1".format(response,
                                           ' + '.join(selected + [candidate]))
            score = smf.ols(formula, data).fit().rsquared_adj
            scores_with_candidates.append((score, candidate))
        scores_with_candidates.sort()
        best_new_score, best_candidate = scores_with_candidates.pop()
        if current_score < best_new_score:
            remaining.remove(best_candidate)
            selected.append(best_candidate)
            current_score = best_new_score
    formula = "{} ~ {} + 1".format(response,
                                   ' + '.join(selected))
    model = smf.ols(formula, data).fit()
    return model

In [ ]:
model = forward_selected(df, 'y')
print(model.model.formula)
print(model.rsquared_adj)

y ~ x2 + 1
0.8307662687716597


In [ ]:
!pip install scikit-learn==0.24.2
# Need this version for SequentialFeatureSelector

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
import sklearn
print(sklearn.__version__)
sorted(sklearn.metrics.SCORERS.keys())

0.24.2


['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_we

In [ ]:
#data = np.array([[1,3,11], [8,5,12], [12, 10, 16],[10, 11, 11], [8, 8, 5], [2,10,15]])
# df = pd.DataFrame(data, columns=['x1', 'x2', 'y'])


In [ ]:
X = df[['x1','x2']].to_numpy()
y = df[['y']].to_numpy()
y

array([[11],
       [12],
       [15],
       [20]])

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
sfs = SequentialFeatureSelector(regr, direction='forward', scoring='neg_mean_squared_error', cv=2)
# sfs = SequentialFeatureSelector(regr, direction='forward', scoring='r2', cv=2)

sfs.fit(X, y)

SequentialFeatureSelector(cv=2, estimator=LinearRegression(),
                          scoring='neg_mean_squared_error')

In [ ]:
sfs.get_params()

{'cv': 2,
 'direction': 'forward',
 'estimator': LinearRegression(),
 'estimator__copy_X': True,
 'estimator__fit_intercept': True,
 'estimator__n_jobs': None,
 'estimator__normalize': False,
 'estimator__positive': False,
 'n_features_to_select': None,
 'n_jobs': None,
 'scoring': 'neg_mean_squared_error'}

In [ ]:
result = sfs.transform(X)
result

array([[ 3],
       [ 5],
       [10],
       [12]])

In [ ]:
X

array([[ 1,  3],
       [ 8,  5],
       [ 2, 10],
       [ 4, 12]])

In [ ]:
sfs.support_

array([False,  True])