In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score

In [2]:
X = np.c_[np.random.randint(0, 10, size=10), 
          np.random.randint(0, 10, size=10)]
y = np.random.randint(0, 10, size=10)

In [3]:
X = np.array([10, 10.001, 10.002]).reshape(-1, 1)
y = np.array([10, 9.99, 9.98])




In [4]:
reg = LinearRegression()
reg.fit(X, y)
reg.coef_, reg.intercept_

(array([-10.]), 109.99999999996442)

In [5]:
r2_score(y, reg.predict(X))
valX = [[0.5]]
valY = [0.49]
regPred = reg.predict(valX)
regError = abs(regPred - valY)
regError

array([104.51])

In [6]:
ridge = Ridge(alpha=0.001)
ridge.fit(X, y)
ridge.coef_, ridge.intercept_

(array([-0.01996008]), 10.189620758483096)

In [7]:
r2_score(y, ridge.predict(X))


0.003988031920052149

In [8]:
ridgePred = ridge.predict(valX)
ridgeError = abs(ridgePred - valY)
ridgeError

array([9.68964072])

In [9]:
lasso = Lasso(alpha=0.001)
lasso.fit(X, y)
lasso.coef_, lasso.intercept_

(array([-0.]), 9.99)

In [10]:
r2_score(y, lasso.predict(X))

0.0

In [11]:
lassoPred = lasso.predict(valX)
lassoError = abs(lassoPred - valY)
lassoError

array([9.5])